# =========================
# SERVER
# =========================
server.address=0.0.0.0
server.port=8080

# =========================
# MONGODB
# =========================
spring.data.mongodb.uri=mongodb+srv://sarthakgupta2303_db_user:Sarthak2025@finestay.i1f1d14.mongodb.net/?appName=finestay
spring.data.mongodb.database=Medicine-tracker
spring.data.mongodb.auto-index-creation=false

# =========================
# GOOGLE OAUTH2
# =========================
spring.security.oauth2.client.registration.google.client-id=584145804994-47ugu2u03r6lr5nj979q4qc0nci52vmq.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

# =========================
# JWT
# =========================
app.jwt.secret=12345678876543211234567898765432
app.jwt.expiration-ms=86400000

# =========================
# FRONTEND
# =========================
app.frontend-url=https://medicine-tracker-web-sarthakgupta023s-projects.vercel.app

# =========================
# LOGGING
# =========================
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.security=INFO