




# =========================
# SERVER
# =========================
server.address=0.0.0.0
server.port=8080

# =========================
# MONGODB
# =========================
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=Medicine-tracker
spring.data.mongodb.auto-index-creation=false

# =========================
# GOOGLE OAUTH2
# =========================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# IMPORTANT: redirect URI
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/{registrationId}

# =========================
# JWT
# =========================
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

# =========================
# FRONTEND
# =========================
app.frontend-url=${FRONTEND_URL:http://localhost:5173}

# =========================
# LOGGING
# =========================
logging.level.com.example.demo=DEBUG
logging.level.org.springframework.security=INFO